name: Code Format

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-bandit flake8-bugbear flake8-builtins flake8-comprehensions flake8-deprecated flake8-isort flake8-print flake8-quotes flake8-todo
          
      - name: Check linting
        run: |
          # ignore list:
          # F722: https://stackoverflow.com/questions/64909849/syntax-error-with-flake8-and-pydantic-constrained-types-constrregex
          # B008: FastAPI uses by design function calls in arguments for dependency injection
          echo -e "[settings]\nline_length=179" > .isort.cfg
          python -m flake8 --max-line-length 179 --ignore=F722,B008 .

