name: Code Format

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-builtins flake8-print flake8-quotes flake8-todo  # flake8-import-order

      - name: Check linting
        run: |
          # ignore list:
          # F722: https://stackoverflow.com/questions/64909849/syntax-error-with-flake8-and-pydantic-constrained-types-constrregex
          python -m flake8 --max-line-length 199 --ignore=F722 .

