name: Releases

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: imagetag
        run: |
          tag=$(echo "${{github.ref_name}}" | cut -dv -f2)
          echo "Docker Image Tag: $tag"
          echo "::set-env name=tag::$tag"
      - name: Create Release
        id: create_release
        if: github.event_name != 'pull_request'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Docker images:
            - ${{ github.repository }}:${{steps.imagetag.outputs.tag}}
            - ghcr.io/${{ github.repository }}:${{steps.imagetag.outputs.tag}}